name: Go Tests and Examples

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test and Run Examples
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: true
        
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Get dependencies
      run: go mod download
      
    - name: Run unit tests
      run: go test -v ./...
      
    - name: Build examples
      run: |
        for dir in examples/*; do
          if [ -d "$dir" ]; then
            echo "Building example: $dir"
            cd "$dir"
            go build -v
            cd -
          fi
        done
      
    - name: Run examples
      run: |
        for dir in examples/*; do
          if [ -d "$dir" ]; then
            echo "Running example: $dir"
            cd "$dir"
            if [ -f "$(basename $dir)" ]; then
              timeout 30s ./$(basename $dir) || echo "Example $dir timed out after 30 seconds"
            fi
            cd -
          fi
        done 